/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Instruction } from "./Instruction";
import { InstructionCountArgs } from "./InstructionCountArgs";
import { InstructionFindManyArgs } from "./InstructionFindManyArgs";
import { InstructionFindUniqueArgs } from "./InstructionFindUniqueArgs";
import { DeleteInstructionArgs } from "./DeleteInstructionArgs";
import { InstructionService } from "../instruction.service";
@graphql.Resolver(() => Instruction)
export class InstructionResolverBase {
  constructor(protected readonly service: InstructionService) {}

  async _instructionsMeta(
    @graphql.Args() args: InstructionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Instruction])
  async instructions(
    @graphql.Args() args: InstructionFindManyArgs
  ): Promise<Instruction[]> {
    return this.service.instructions(args);
  }

  @graphql.Query(() => Instruction, { nullable: true })
  async instruction(
    @graphql.Args() args: InstructionFindUniqueArgs
  ): Promise<Instruction | null> {
    const result = await this.service.instruction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Instruction)
  async deleteInstruction(
    @graphql.Args() args: DeleteInstructionArgs
  ): Promise<Instruction | null> {
    try {
      return await this.service.deleteInstruction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
